export const ERROR_DEFAULT = 'DEFAULT';
export const ERROR_CONFIRM_CODE = 'CONFIRM_CODE_ERROR';
export const ERROR_CANNOT_LOGIN_WITH_EXTENSION = 'CANNOT_LOGIN_WITH_EXTENSION';
export const ERROR_USER_NOT_ACTIVE = 'USER_NOT_ACTIVE';
export const ERROR_EMAIL_EXISTS = 'EMAIL_EXISTS';
export const ERROR_EMAIL_NOT_EXISTS = 'EMAIL_NOT_EXISTS';
export const ERROR_ACTIVE_CODE_INVALID = 'ACTIVE_CODE_INVALID';
export const ERROR_PARAMETERS = 'PARAMETERS_ERROR';
export const SERVER_ERROR = 'SERVER_ERROR';
export const ERROR_EMAIL_KAIBASE_EXISTS = 'EMAIL_KAIBASE_EXISTS';

